#!/usr/bin/env python3
"""Create 7606-train-template task plugins tasks/ms_<task> for scripts/export_demos.py files.

Each plugin is a verbatim copy of the template's tasks/task_06 (PlugCharger, state obs)
with only config.py rewritten: env id and control mode come from the exported demo's
JSON, obs/action dims from its .export_info.json, the eval episode length from the command
line. Data loading, models, policy and environment code stay the template's own.
Standard library only.

    make_template_tasks.py --template-dir ~/teammates/7606-train-template \\
        pickcube=100=data/smoke0925b/train/PickCube-v1/motionplanning/trajectory.state.pd_ee_delta_pos.physx_cpu.h5
"""

import argparse
import json
import pprint
import shutil
from pathlib import Path

SOURCE_TASK = "task_06"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--template-dir", type=Path, required=True)
    parser.add_argument("tasks", nargs="+", help="<task>=<max_episode_steps>=<exported training demo .h5>")
    args = parser.parse_args()

    tasks_dir = args.template_dir / "tasks"
    base = {}
    exec((tasks_dir / SOURCE_TASK / "config.py").read_text(encoding="utf-8"), base)
    base_config = base["TASK_CONFIG"]

    for item in args.tasks:
        task, steps, path = item.split("=", 2)
        dataset = Path(path).resolve()
        meta = json.loads(dataset.with_suffix(".json").read_text(encoding="utf-8"))
        summary = json.loads(dataset.with_name(dataset.stem + ".export_info.json").read_text(encoding="utf-8"))
        assert summary["split"] == "train", f"{dataset} is a {summary['split']} file"
        config = dict(base_config)
        config.update(
            task_name=meta["env_info"]["env_id"],
            obs_dim=summary["obs_dim"],
            action_dim=summary["action_dim"],
            max_episode_steps=int(steps),
            data_dir=str(dataset.parent),
            dataset=str(dataset),
            control_mode=summary["control_mode"],
        )
        assert config["obs_mode"] == "state", "the template trains on the flat traj_N/obs vector"
        changed = [key for key in config if config[key] != base_config.get(key)]

        plugin = tasks_dir / f"ms_{task}"
        if plugin.exists():
            shutil.rmtree(plugin)
        shutil.copytree(tasks_dir / SOURCE_TASK, plugin, ignore=shutil.ignore_patterns("__pycache__"))
        (plugin / "config.py").write_text(
            f"# Generated by dp-manip scripts/smoke/make_template_tasks.py from tasks/{SOURCE_TASK}/config.py.\n"
            f"# Changed keys: {', '.join(changed)}\n"
            f"TASK_CONFIG = {pprint.pformat(config, sort_dicts=False)}\n",
            encoding="utf-8")
        print(f"{plugin.name}: {config['task_name']} {config['control_mode']} obs {config['obs_dim']} "
              f"action {config['action_dim']} steps {config['max_episode_steps']} <- {dataset}")


if __name__ == "__main__":
    main()
